### PR TITLE
Update maguro props to 4.0.4 IMM76D

### PR DESCRIPTION
**Pull request by KalimAz**

### CODE REVIEW

**Comment by KalimAz** [comment]
codeworks, yes, I miss becase they are not at google stuff. Readded

**Comment by blunden** [comment]
Is it just me being blind or do you never actually add the new files?

**Comment by KalimAz** [comment]
blunden here is udated the file https://github.com/KalimAz/proprietary_vendor_samsung/commit/8d83427106693d1b77aa01d74872d06ec0e2ae4b

here is removed the old file and modified the mk file https://github.com/KalimAz/proprietary_vendor_samsung/commit/9e24e45b983d5fdf6b2c9d9c3a572b2b9e4c60c0

**Comment by blunden** [comment]
So the GPU driver is identical to the 4.0.3 one? If so, then it makes sense. As soon as the OTA or factory image is released we need to update the NFC firmware too most likely.

https://code.google.com/intl/sv-SE/android/nexus/drivers.html#maguroimm76d

**Pull request merged**
