### PR TITLE
d2: update blobs: from verizon VRBMA2 4.1.2 leak

### PR DESCRIPTION
**Pull request by invisiblek**

### CODE REVIEW

**Comment by ciwrl** [comment]
As this is for -common, I'll leave it for Steve or someone else to confirm and merge

**Comment by eljef** [comment]
@cyanogen , @koush , or @rmcc need to comment on this or close.

**Comment by invisiblek** [comment]
or @noobnl 

there's a chance this will break RIL on other d2 variants, so it most definitely needs to be tested

**Comment by shareefalis** [comment]
I made my decision, no beta blobs.

**Comment by rmcc** [comment]
FYI: Leaked binaries are generally disadvised, but possible if they're clearly the better alternative (i.e., provide otherwise missing functionality). Leaked binaries that require the user to install a leaked firmware component (bootloader, baseband, and the like) are a definite no-no.

**Pull request closed without merging**
