### PR TITLE
hlte: Return time_daemon to working state

### PR DESCRIPTION
**Pull request by wilfredlams**
Return time_daemon to old version to fix the time issue in hltexx

### CODE REVIEW

**Comment by wilfredlams** [comment]
Anybody?

**Comment by DAGr8** [comment]
i confirm fixed it here ,merge please ?

**Comment by DAGr8** [comment]
actually it reverted again , so its not fully working . not sure what else is missing

**Comment by wilfredlams** [comment]
What do you mean it reverted?

**Comment by DAGr8** [comment]
well i flashed rom , unchecked time zone was fine , rebooted , then posted comment , 15 minutes later timezzone was off again .. and its still of !

On Monday, April 14, 2014 9:32:19 PM, Wilfred Lam notifications@github.com wrote:

What do you mean it reverted?

**Comment by wilfredlams** [comment]
You need to reboot your phone twice after you patch it, I have no problem with it.

**Comment by DAGr8** [comment]
hmm i just reflashed seems fine now.. if its still fine in 24hrs ill +1 you again maybe i reflahed wrong build somehow

On Monday, April 14, 2014 9:56:34 PM, Wilfred Lam notifications@github.com wrote:

You need to reboot your phone twice after you patch it, I have no problem with it.

**Comment by DAGr8** [comment]
it reverted again this morning so im not sure whats wrong but the fix is 'unstable' to say the least' cell tower issue maybe?

On Monday, April 14, 2014 10:05:21 PM, Renaud dagr82003@yahoo.com wrote:

hmm i just reflashed seems fine now.. if its still fine in 24hrs ill +1 you again maybe i reflahed wrong build somehow
On Monday, April 14, 2014 9:56:34 PM, Wilfred Lam notifications@github.com wrote:

You need to reboot your phone twice after you patch it, I have no problem with it.

**Comment by wilfredlams** [comment]
What variant do you use? I haven't had a single problem on the N9005.

**Comment by DAGr8** [comment]
n900w8 , it might be related to cell signal if you try to switch towers do you keep the same signal ?

On Tuesday, April 15, 2014 7:27:45 AM, Wilfred Lam notifications@github.com wrote:

What variant do you use? I haven't had a single problem on the N9005.

**Comment by wilfredlams** [comment]
don't know what you mean by same signal.

**Comment by DAGr8** [comment]
typo meant timezone

**Comment by wilfredlams** [comment]
Anyone else tried and is it working for you?

**Comment by wilfredlams** [comment]
To DAGr8, you should only test this with all auto timezone and auto date and time off. Otherwise the wrong time you meant might be your carrier giving you the wrong time and not related to this patch.

**Comment by DAGr8** [comment]
if i set the time in manually and then go in and make sure ONLY auto timezone is checked it will either modify the time by 4 hours instantly (wrong timezone) or it will stay the same then a few hours if not minutes modify it by 4 hours .. as i said , this patch made it better but didnt fix it for n900w8

On Thursday, April 17, 2014 3:41:41 AM, Wilfred Lam notifications@github.com wrote:

To DAGr8, you should only test this with all auto timezone and auto date and time off. Otherwise the wrong time you meant might be your carrier giving you the wrong time and not related to this patch.

**Comment by wilfredlams** [comment]
what about is the auto timezone is off? does it still do it? because I am thinking it might be your carrier. all time_daemon supposed to do is to save the time to the rtc when you modify it and reuse that value when you reboot. If your time is fine when you reboot without using auto date/time and auto timezone, it has done it's job. The rest is not related to the time_daemon.

**Comment by wilfredlams** [comment]
There is a person at xda that use your variant that claims that it works fine on him.
http://forum.xda-developers.com/showthread.php?p=51900798#post51900798

**Comment by wilfredlams** [comment]
@noobnl or @cyanogen , are you around? could you test if this works for you? I really hope we can merge this.

**Comment by broodplank** [comment]
I believe this is a better fix
https://android-review.googlesource.com/#/c/89852/

**Comment by wilfredlams** [comment]
Hi @broodplank, I don't think the problem is with displaying the clock value in the status bar, it is the wrong time recorded in the rtc, because recovery also shows the wrong time.

**Comment by broodplank** [comment]
@wilfredlams ok I didn't know it was about RTC time, recovery is for me also 1 hour off actual time. So maybe this will become handy for me as well. Thanks!

**Comment by wilfredlams** [comment]
@DAGr8 I forgot to ask, did you set the correct permission for the time_daemon when you replace it?

**Pull request merged**
