### PR TITLE
epicmtd: Remove liblight blob since it's now built from source.

### PR DESCRIPTION
**Pull request by nubecoder**
liblight is built from source as of this change:
http://review.cyanogenmod.com/#/c/18398/
So remove the proprietary blob.

### CODE REVIEW

**Comment by nubecoder** [comment]
Crap, I'm now seeing this was already merged..
Well partially..  Maybe just close this out and remove the actual file in a new commit.

I'll leave open for now, do as you please.

**Comment by UberPinguin** [comment]
It looks like bbelos' commit does the same thing, though I'm not sure why yours and his seem to have different ordering of the blobs.
See https://github.com/koush/proprietary_vendor_samsung/pull/61.

What's your opinion, nubecoder?

**Comment by chirayudesai** [comment]
@UberPinguin gingerbread vs ics
noobnl's commit is for gb, while bbelos' commit is for ics.

**Comment by nubecoder** [comment]
chirayudesai is partially right, you linked the wrong pull req. 
( Here's the right one: https://github.com/koush/proprietary_vendor_samsung/pull/71 )
But then failed by calling my noobnl. ;]

Anyway, the only difference from the previous pull request, is that this one also removes the actual file (in proprietary folder).  Otherwise, no difference.

=]

**Comment by nubecoder** [comment]
ps -Sorry for all the confusion.

**Pull request merged**
