### PR TITLE
msm8976 + gts210vewifi: Update blobs from T813XXS2BSG1. (Vendor-Security-Patch 01-07-2019)

### PR DESCRIPTION
**Pull request by LukasKraehling**
- Newest international firmware image for T813
- Tested on T813

### CODE REVIEW

**Comment by npjohnson** [comment]
This device has no activity on 17.1, 16.0 would make sense here?

**Comment by LukasKraehling** [comment]
@npjohnson https://forum.xda-developers.com/tab-s2/development/rom-lineageos-17-1-t4070161 
Should i create two requests for LOS 16.0 and LOS 17.1 ?

**Comment by npjohnson** [comment]
That ROM has no sources pushed to official repos, and therefore, no place here.

16.0 could likely, but syphry will have to review.

**Comment by LukasKraehling** [comment]
@npjohnson Ok, I hope he approves. But wouldn't it be useful for official 17.1 ROMs in the future even if there is none now ?

**Pull request closed without merging**
