### PR TITLE
jf: Remove unused graphics libraries

### PR DESCRIPTION
**Pull request by zwliew**
Change-Id: I77885d66c295937f3d166de81d18f0fff92596af

### CODE REVIEW

**Comment by javelinanddart** [comment]
I'm pretty sure @arco removed these because he removed dev blobs, 99% sure flo release still have them which is where we're getting our blobs

**Comment by zwliew** [comment]
I tried grepping the graphics libraries and I couldn't actually find an instance where libplayback_adreno.so and libc2d30.so are being used

**Comment by zwliew** [comment]
-1 I'll reverify this again.

**Comment by zwliew** [comment]
This should be good to go. @arco

**Pull request merged**
