### PR TITLE
Add jfltegsm

### PR DESCRIPTION
**Pull request by attn1**

### CODE REVIEW

**Comment by shareefalis** [comment]
gsm?

**Comment by ciwrl** [comment]
He's attempting to unify the GSM variants into one build.

**Comment by chris41g** [comment]
maybe a better name.. like jfltexx-common or something.. but ALL the phones are gsm capabale afaict

**Comment by attn1** [comment]
GSM vs CDMA/GSM.  GSM is more appropriate than NON-CDMA.

**Comment by shareefalis** [comment]
nope, should be merged into jf common.

**Comment by shareefalis** [comment]
nope!

**Pull request closed without merging**
