### PR TITLE
klte: update gps libs Use gps libs from sprint

### PR DESCRIPTION
**Pull request by deVorteX**
…rietary gps

Change-Id: I90de484119de9219e83ccfdee92334e24f10ff65

### CODE REVIEW

**Comment by javelinanddart** [comment]
OT: This is by far one of the worst commit messages i've seen
Real: barring that, has this only been tested on Sprint or on multiple klte variants?

**Comment by deVorteX** [comment]
Sorry about the commit message, I was trying to head out, and wanted to get my point across.

This has been tested on klte, I'm using the gps libs that were added earlier for kltespr. Ethan said on kltespr his gps worked, but us on klte had no luck. I simply copied the sprint libs to klte and it's working fine so far.

**Comment by javelinanddart** [comment]
Sounds good, just was a little confused

**Comment by OzzysCmAcc** [comment]
if someone could merge this would be fine

**Comment by intervigilium** [comment]
Don't merge this yet.

**Comment by deVorteX** [comment]
I think albinoman has a better more proper fix for this.

**Pull request closed without merging**
