### PR TITLE
jf & jf-gsm: Update blobs

### PR DESCRIPTION
**Pull request by zwliew**
- Update all the jf-gsm blobs from I9505GUEUDPF1
- Remove unused DivX dependencies from jf
- Revert to flo Adreno blobs to prevent RenderThread crashes

### CODE REVIEW

**Comment by javelinanddart** [comment]
Zhao mentioned these were working fine for him, I'm going to give them a shot in a little bit

**Comment by B--B** [comment]
I'm trying this blobs too, no issues after a week of usage and none of my testers reported problems, for me are fine

**Comment by javelinanddart** [comment]
@invisiblek I think this is a go

**Comment by zwliew** [comment]
Please test to see whether there are still RenderThread app crashes with flo's Adreno blobs. More testers would be nice :)

**Comment by zwliew** [comment]
The crash should look something like this:

"**\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
CM Version: '13.0-20160708-NIGHTLY-jfltexx'
Build fingerprint: 'samsung/jfltexx/jflte:5.0.1/LRX22C/I9505XXUHOB7:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 2429, tid: 2957, name: RenderThread  >>> com.android.dialer <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
    r0 00000000  r1 9c6348b0  r2 00000000  r3 976bf0e0
    r4 b06b1f64  r5 9dfa57f0  r6 00000000  r7 9dfa57f0
    r8 b06b1f64  r9 9dfa57f0  sl 00000000  fp 9d2d1180
    ip b6ce2974  sp 9fb762e8  lr b6cbc8c1  pc a7ece2d8  cpsr 400e0030

backtrace:
    #00 pc 000062d8  /system/vendor/lib/libgsl.so (gsl_linkedlist_allocnode+41)
    #01 pc 0001dd53  /system/vendor/lib/libgsl.so
    #02 pc 0001e8d7  /system/vendor/lib/libgsl.so
    #03 pc 00007651  /system/vendor/lib/libgsl.so (gsl_command_issueib_with_alloc_list+1308)
    #04 pc 0000782d  /system/vendor/lib/libgsl.so (gsl_command_issueib_sync+440)
    #05 pc 00080bf7  /system/vendor/lib/egl/libGLESv2_adreno.so (rb_cmdbuffer_issue+1214)
    #06 pc 00088525  /system/vendor/lib/egl/libGLESv2_adreno.so (rb_perform_skip_resolve+508)
    #07 pc 000887ff  /system/vendor/lib/egl/libGLESv2_adreno.so (rb_perform_resolve+166)
    #08 pc 00088bdb  /system/vendor/lib/egl/libGLESv2_adreno.so (rb_resolve+646)
    #09 pc 0008dd15  /system/vendor/lib/egl/libGLESv2_adreno.so (rb_surface_swap+268)
    #10 pc 0006e0e9  /system/vendor/lib/egl/libGLESv2_adreno.so (gl2_surface_swap+72)
    #11 pc 000603c9  /system/vendor/lib/egl/libGLESv2_adreno.so (oglSwapBuffer+208)
    #12 pc 00014958  /system/vendor/lib/egl/libEGL_adreno.so (qeglDrvAPI_eglSwapBuffers+2032)
    #13 pc 00014215  /system/lib/libEGL.so (eglSwapBuffersWithDamageKHR+444)
    #14 pc 0001b98f  /system/lib/libhwui.so
    #15 pc 00019c2b  /system/lib/libhwui.so
    #16 pc 0001acd3  /system/lib/libhwui.so
    #17 pc 0001d9ed  /system/lib/libhwui.so (_ZN7android10uirenderer12renderthread12RenderThread10threadLoopEv+100)
    #18 pc 000103dd  /system/lib/libutils.so (_ZN7android6Thread11_threadLoopEPv+140)
    #19 pc 0005f99f  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+70)
    #20 pc 00046f41  /system/lib/libc.so (_ZL15__pthread_startPv+32)
    #21 pc 00018c55  /system/lib/libc.so (__start_thread+8)
"

**Comment by zwliew** [comment]
The device-side change is here: http://review.cyanogenmod.org/#/c/153691/

**Comment by javelinanddart** [comment]
+1, this works well for me, both commits

**Comment by B--B** [comment]
Good for me too, no crashes or other issues after a day of usage 👍

**Comment by zwliew** [comment]
Do you know anyone who faced the crashes before, and whether this fixed the crashes for them?

**Comment by javelinanddart** [comment]
@B--B @smeroni68

Did you testers report anything that was off?

**Comment by zwliew** [comment]
Well, I, for one, no longer face the crashes, so that's something I guess.

**Comment by zwliew** [comment]
@invisiblek This seems ready

**Comment by B--B** [comment]
@zwliew I had only a crash with your libs some days ago (hangouts), that's why I decided to try libraries provided by Paul, 2 days of testing and no crashes in 3 different phones!

**Comment by javelinanddart** [comment]
@invisiblek Can you merge this?

**Comment by javelinanddart** [comment]
@chirayudesai Thank you!

**Pull request merged**
