### PR TITLE
New Blobs from S4 Google Edition

### PR DESCRIPTION
**Pull request by jumoog**

### CODE REVIEW

**Comment by nardholio** [comment]
I don't think jf ever shipped with geofence. Doesn't mean it should be removed

**Comment by invisiblek** [comment]
how does this not break wifi by removing these nvram's?
not shipping libc2d2_a3xx.so ?
yea, libgeofence was added later, we don't want to get rid of it.

**Comment by jumoog** [comment]
I copied all files that i found (i used find)

I used -> http://forum.xda-developers.com/showthread.php?t=2547739 since Google provides on Updates and not full ROM's

**Comment by arco** [comment]
@invisiblek, libc2d2_a3xx is obsolete.
See https://github.com/TheMuppets/proprietary_vendor_samsung/commit/6d85fae7ad72bc9c9d0d0a5558510f735610618c

**Pull request closed without merging**
