### PR TITLE
add fascinate vendor blobs and EC01 radio

### PR DESCRIPTION
**Pull request by jt1134**

### CODE REVIEW

**Comment by koush** [comment]
Do you have CM being built frmo source?

**Comment by jt1134** [comment]
partially, yes

**Comment by koush** [comment]
Why do you want these blobs in here? Are you trying to fully merge?

**Comment by jt1134** [comment]
I'm in the middle of fully merging. Just sent this along because it was small and didn't break the build yet :p Feel free to ignore for now. More is on the way.

**Pull request closed without merging**
