### PR TITLE
klte: thermal-engine needs libthermalioctl

### PR DESCRIPTION
**Pull request by nuclearmistake**
Change-Id: I87b8262658986da1b3108d596980c7c93bad0fe4

### CODE REVIEW

**Comment by intervigilium** [comment]
Can you note which firmware package you took this library from?

**Comment by nuclearmistake** [comment]
G900V (vzw dev edition)

I can amend the msg if you'd like

**Comment by Albinoman887** [comment]
It would probably be better to grab from G900F. I can upload it if you want

**Comment by nuclearmistake** [comment]
Go ahead. I'm not attached

**Comment by Albinoman887** [comment]
turns out the files are identical....

**Comment by Albinoman887** [comment]
So what we doing with this...it should be merged. the commit message just needs cleaning up. I can up a new pr with corrected message and retain authorship if you want...

**Comment by nuclearmistake** [comment]
changed commit msg

**Pull request merged**
