### PR TITLE
toro: add props to get VZW apps working (ie: NFL Mobile)

### PR DESCRIPTION
**Pull request by fitsnugly**
extract-files.sh was updated Jan 8 for these props: http://review.cyanogenmod.com/#change,11483

### CODE REVIEW

**Comment by bekriebel** [comment]
For these to be included, you also need to update the Android.mk file to add LOCAL_MODULE entries for the two APKs and update device-toro.mk file to include the xml files in PRODUCT_COPY_FILES and the APKs in PRODUCT_PACKAGES.

**Comment by fitsnugly** [comment]
I'm still learning here, so bare with me, but I thought the device-vendor-blobs.mk (which was updated with the extract-files.sh changes) handled copying the files into the build?

**Comment by bekriebel** [comment]
If it was ran, it would do the trick. However, Google has commented that extract-files is not fully maintained and therefore not guaranteed to be accurate in their drops. Because of this, I haven't bothered maintaining it either and extract-files.sh is never used during the build process.

**Comment by fitsnugly** [comment]
http://review.cyanogenmod.com/#change,12995

**Comment by bekriebel** [comment]
I mean in this repo, not in the device tree.  Make the changes in proprietary_vendor_samsung/toro/device-toro.mk and proprietary_vendor_samsung/toro/proprietary/Android.mk

**Comment by fitsnugly** [comment]
derp, sorry, how's that

**Comment by bekriebel** [comment]
I think the comment in the PRODUCT_PACKAGES will actually screw up the multi-line stuff. Blow away the "#Cell information. Dial _#_#786#_#_" stuff from that line. In its place, can you add a new section Just above Disabled PRODUCT_PACAKGES to store descriptions of what is turned on. e.g.:

# PRODUCT_PACKAGE descriptions

# RTN - Cell information. Dial _#_#786#_#_

# VZWAPNLib - <description>

# VZWAPNService <description>

I just want to make sure we keep track of what things are so we don't mess them up in the future :-)

Can you then squish the commits together so that there is just one commit that adds the files and updates the makefiles? That may require a new pull request - I'm not sure how github handles the requests when you change history like that.

**Comment by bekriebel** [comment]
Ack! Apperently using a hash does stuff to comment formatting :-) That giant text should really just have "#" in front of them to make them comments in the make file.

**Comment by fitsnugly** [comment]
will do! again, thanks for the help, doing the best I can to help out :)

**Pull request closed without merging**
