### PR TITLE
Add gtaxlwifi - credit Valera1978

### PR DESCRIPTION
**Pull request by darran-kelinske-fivestars**

### CODE REVIEW

**Comment by darran-kelinske-fivestars** [comment]
did I do something wrong?

**Comment by npjohnson** [comment]
"Your Name committed 7 hours ago"

**Comment by npjohnson** [comment]
you need an actual author at minimum, and preferably explain why you're doing this.

**Comment by Exodusnick** [comment]
What do you say?

 

salute 
christian 
 

Gesendet: Dienstag, 18. Juni 2019 um 04:27 Uhr
Von: "Nolen Johnson" <notifications@github.com>
An: TheMuppets/proprietary_vendor_samsung <proprietary_vendor_samsung@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [TheMuppets/proprietary_vendor_samsung] Add gtaxlwifi - credit Valera1978 (#1116)


you need an actual author at minimum, and preferably explain why you're doing this.

**Comment by darran-kelinske-fivestars** [comment]
Didn't realize it said "Your Name" on the commit - looking at what to do

**Pull request closed without merging**
