### PR TITLE
smdk4412: add another camera blob

### PR DESCRIPTION
**Pull request by invisiblek**
Change-Id: Ib5b48d5967e50fb3cb7d174e45f8cb020d4efa5d

### CODE REVIEW

**Comment by sspencer10** [comment]
Lol, ok

**Comment by invisiblek** [comment]
heh, @sspencer10 i didnt see you already had a commit for this =P

**Comment by invisiblek** [comment]
nvm, yours was for d2

**Comment by sspencer10** [comment]
Sorry, didnt notice yours wasnt. Ive been buggin him to merge and seen u
pulled and got merged the wh one in 5 min...just thought it was funny. If u
want to submit it for d2 that would b cool, ud probably have better luck
than i

**Comment by puchu** [comment]
yeah please commit, i need this firmware too

**Pull request merged**
