### PR TITLE
klte-common: Update Adreno drivers.

### PR DESCRIPTION
**Pull request by Albinoman887**
- Camera was randomly crashing while taking darker shots. Updating adreno
  libs seems to fix this issue.
- Adreno package version:
  AU_LINUX_ANDROID_LNX.LA.3.5.2.2_RB1.04.04.04.087.028_msm8974

Change-Id: Ifda5714bb901ffe11c02bd286959b070b41f5544

### CODE REVIEW

**Comment by intervigilium** [comment]
Does it actually fix the issue, or is this just coincidental?

**Comment by Albinoman887** [comment]
Yes it actually fixes the issue with camera and dark images

**Comment by Albinoman887** [comment]
So this gonna get merged then ?

**Comment by Albinoman887** [comment]
Its not by accident . the adreno drivers were crashing during the photo with an odd error

**Comment by Albinoman887** [comment]
Please? Its an important fix

**Comment by intervigilium** [comment]
That's kind of weird, I wonder if the camera libs were doing any GPU offload.

**Comment by Albinoman887** [comment]
How would I know if they were doing offloading of some kind

**Pull request merged**
