### PR TITLE
d2usc proprietary files

### PR DESCRIPTION
**Pull request by jpaulwaitedev**
added proprietary files for the us cellular sch-r530 d2usc

### CODE REVIEW

**Comment by shareefalis** [comment]
we need to talk in #cyanogenmod-dev in freenode irc server

**Comment by jpaulwaitedev** [comment]
ok one sec

**Comment by jpaulwaitedev** [comment]
== #cyanogenmod-dev Cannot join channel (+r) - you need to be identified with services

sorry, not used to irc.  any help?

**Comment by shareefalis** [comment]
you need to be regestered with freenode

**Pull request closed without merging**
