### PR TITLE
jf: Update blobs

### PR DESCRIPTION
**Pull request by zwliew**

### CODE REVIEW

**Comment by javelinanddart** [comment]
We really should use Google blobs, not Qcom's dev blobs. Those are release ready, these are not.

**Comment by ghost** [comment]
These actually seem to work great. I also added libplayback_adreno.so like in javlinanddart's pull request. Seems much snappier, but I'm not sure if its the new kernel changes or the blobs. I haven't seen any crashes tho.

**Comment by javelinanddart** [comment]
That's mixing and matching blobs, not really a good idea. I would prefer
using the ones in my pull req but those are June not July blobs

**Comment by zwliew** [comment]
These blobs do in fact fix the RenderThread issues faced on the current Adreno blobs. Don't think I notice any performance differences though.

**Comment by ghost** [comment]
Must be the kernel changes then since I hadn't synced for quite awhile.

**Comment by javelinanddart** [comment]
Are you on F2FS?

**Comment by ghost** [comment]
Yes I am.

**Comment by javelinanddart** [comment]
Maybe it's just me, maybe it's placebo, but the new F2FS seems to perform
well or even better, and Zhao pushed a bunch of performance improvements in
the kernel. I doubt you'd notice a marked improvement from blob update.

**Pull request merged**
