### PR TITLE
Pre-KK time_daemon and libtime_genoff.so for jactive

### PR DESCRIPTION
**Pull request by spegelius**
- time value update to /data fails with KK blobs and in next
  boot, time is wrong. Some apps (Whatsapp for example) complain
  about this
- error is: Daemon:genoff_handler: Socket client is not qualcomm
  time service, uid: 1001, pid: 1292
- older blobs are working properly

### CODE REVIEW

**Comment by intervigilium** [comment]
Is this still necessary?

**Comment by spegelius** [comment]
Yes

**Comment by spegelius** [comment]
Is this forgotten or rejected? Time resets way off with nightlies

**Comment by arco** [comment]
I'd recommend you implement TimeService.apk blob. It seems to have fixed all time related issues on my device.

https://github.com/CyanogenMod/android_device_samsung_serrano-common/commit/cb89548f8ddaae025fb4f45871057d4949c4f6fe

**Pull request closed without merging**
