### PR TITLE
Adding Samsung Galaxy S3 DoCoMo (d2dcm Japan)

### PR DESCRIPTION
**Pull request by xInterlopeRx**
Please merge for downstream device support. Thank you. There is evidence here of this repo at work: http://www.oudhitsquad.com/android/?dir=Samsung/d2dcm I haven't had any bug reports in a while, and my test device work fully running CM, Slim and Carbon.

### CODE REVIEW

**Comment by invisiblek** [comment]
This is defined in d2-common:
USE_CAMERA_STUB := false

Why are you shipping wifi nvram? (these should go in d2-common if anything, my guess is they are not needed)
Why are you defining wallpapers/overlays in your vendor mk? (definitely not the place for this)
make_ext4fs and ext4sd are unecessary...as is libDivxDvm (in d2-common) 
What do you need libcordon for?
(These questions are based on the fact that no other d2 variant has all this stuff in it. d2-common should do everything except your two ril blobs)

**Comment by xInterlopeRx** [comment]
I'll clean it up and resubmit. This variant has a driver called felica that
DoCoMo adds. It's an NFC device they add that is used by their mass transit
system for payment at entry. The d2dcm also has an FM radio and television
tuner with an external antenna. These systems I cannot test but they are
differences I thought I should mention.

On Mon, Jan 20, 2014 at 7:01 AM, Dan Pasanen notifications@github.comwrote:

> This is defined in d2-common:
> USE_CAMERA_STUB := false
> 
> Why are you shipping wifi nvram? (these should go in d2-common if
> anything, my guess is they are not needed)
> Why are you defining wallpapers/overlays in your vendor mk? (definitely
> not the place for this)
> make_ext4fs and ext4sd are unecessary...as is libDivxDvm (in d2-common)
> What do you need libcordon for?
> (These questions are based on the fact that no other d2 variant has all
> this stuff in it. d2-common should do everything except your two ril blobs)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TheMuppets/proprietary_vendor_samsung/pull/391#issuecomment-32761255
> .

## 

_John Kirk_
915-799-1553
FAX 915-988-2601
Norwex Clean Living Products http://heidikirk.norwex.biz
Thirty-One https://www.mythirtyone.com/heidikirk/
OUDHitSquad http://www.oudhitsquad.com/index.php

**Comment by xInterlopeRx** [comment]
I changed everything mentioned in your comments invisiblek. I'll have to test/diff nvram because I know textually they are different, but I don't know how the device behaves with the common files. Should I create a new pull request and close this one? I'm not sure how this works. Thanks.

**Comment by xInterlopeRx** [comment]
Sorry, changed but did not push changes. Thanks for your patience.

**Comment by nardholio** [comment]
start a new clean branch. you have 4 commits here, including one for galaxy tab.

**Comment by xInterlopeRx** [comment]
OK.

**Pull request closed without merging**
