### PR TITLE
Added missing proprietary files for Samsung Vendor.

### PR DESCRIPTION
**Pull request by PaulW**
Added missing proprietary files.  This is what has been causing issues with nightly builds of Crespo sometimes being buggy/slow.  Compare nightly #81 to nightly #83 to see, as #81 is missing files.  Also added proprietary libs for other devices which seemed to be missing (grabbed all via extract-files.sh from relavent devices)

### CODE REVIEW

**Comment by atinm** [comment]
Incorrect changes to aries-common. Closing.

**Comment by coolya** [comment]
I have no clue what you are trying to do but what you did won't fix anything. You even commited files that are totally unused.

**Comment by PaulW** [comment]
I ran all the extract-files.sh scripts by mistake, only meant to upload crespo proprietary files.  Basically, when compiling using the vendor files, it is missing quite a few, so compiled ROM's always run slow, have bluetooth/gps issues (ie not working.)

Files which were missing are (just crespo):

```
system/etc/gps.conf
system/lib/libpn544_fw.so
system/vendor/bin/gpsd
system/vendor/bin/pvrsrvinit
system/vendor/etc/gps.xml
system/vendor/firmware/bcm4329.hcd
system/vendor/firmware/nvram_net.txt
system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so
system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so
system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so
system/vendor/lib/hw/gps.s5pc110.so
system/vendor/lib/hw/gralloc.s5pc110.so
system/vendor/lib/libglslcompiler.so
system/vendor/lib/libIMGegl.so
system/vendor/lib/libpvr2d.so
system/vendor/lib/libpvrANDROID_WSEGL.so
system/vendor/lib/libPVRScopeServices.so
system/vendor/lib/libsrv_init.so
system/vendor/lib/libsrv_um.so
system/vendor/lib/libusc.so
```

**Comment by atinm** [comment]
Re-submit the pull request with just the files you want to push. Hopefully someone who is doing crespo can do the pull after that.

**Pull request closed without merging**
